const countries = {
  AF: "Afeganistão",
  ZA: "África do Sul",
  AL: "Albânia",
  DE: "Alemanha",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antártida",
  AG: "Antígua e Barbuda",
  SA: "Arábia Saudita",
  DZ: "Argélia",
  AR: "Argentina",
  AM: "Armênia",
  AW: "Aruba",
  AU: "Austrália",
  AT: "Áustria",
  AZ: "Azerbaijão",
  BS: "Bahamas",
  BH: "Bahrein",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Bélgica",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermudas",
  BO: "Bolívia",
  BA: "Bósnia-Herzegóvina",
  BW: "Botsuana",
  BR: "Brasil",
  BN: "Brunei",
  BG: "Bulgária",
  BF: "Burkina Fasso",
  BI: "Burundi",
  BT: "Butão",
  CV: "Cabo Verde",
  CM: "Camarões",
  KH: "Camboja",
  CA: "Canadá",
  IC: "Canárias",
  KZ: "Cazaquistão",
  EA: "Ceuta e Melilla",
  TD: "Chade",
  CL: "Chile",
  CN: "China",
  CY: "Chipre",
  SG: "Cingapura",
  CO: "Colômbia",
  KM: "Comores",
  CG: "Congo",
  KP: "Coréia do Norte",
  KR: "Coréia do Sul",
  CI: "Costa do Marfim",
  CR: "Costa Rica",
  HR: "Croácia",
  CU: "Cuba",
  CW: "Curaçao",
  DG: "Diego Garcia",
  DK: "Dinamarca",
  DJ: "Djibuti",
  DM: "Dominica",
  EG: "Egito",
  SV: "El Salvador",
  AE: "Emirados Árabes Unidos",
  EC: "Equador",
  ER: "Eritréia",
  SK: "Eslováquia",
  SI: "Eslovênia",
  ES: "Espanha",
  US: "Estados Unidos",
  EE: "Estônia",
  ET: "Etiópia",
  FJ: "Fiji",
  PH: "Filipinas",
  FI: "Finlândia",
  FR: "França",
  GA: "Gabão",
  GM: "Gâmbia",
  GH: "Gana",
  GE: "Geórgia",
  GI: "Gibraltar",
  GB: "Grã-Bretanha (Reino Unido, UK)",
  GD: "Granada",
  GR: "Grécia",
  GL: "Groelândia",
  GP: "Guadalupe",
  GU: "Guam (Território dos Estados Unidos)",
  GT: "Guatemala",
  GG: "Guernsey",
  GY: "Guiana",
  GF: "Guiana Francesa",
  GN: "Guiné",
  GQ: "Guiné Equatorial",
  GW: "Guiné-Bissau",
  HT: "Haiti",
  NL: "Holanda",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungria",
  YE: "Iêmen",
  BV: "Ilha Bouvet",
  AC: "Ilha de Ascensão",
  CP: "Ilha de Clipperton",
  IM: "Ilha de Man",
  CX: "Ilha Natal",
  PN: "Ilha Pitcairn",
  RE: "Ilha Reunião",
  AX: "Ilhas Aland",
  KY: "Ilhas Cayman",
  CC: "Ilhas Cocos",
  CK: "Ilhas Cook",
  FO: "Ilhas Faroes",
  GS: "Ilhas Geórgia do Sul e Sandwich do Sul",
  HM: "Ilhas Heard e McDonald (Território da Austrália)",
  FK: "Ilhas Malvinas",
  MP: "Ilhas Marianas do Norte",
  MH: "Ilhas Marshall",
  UM: "Ilhas Menores dos Estados Unidos",
  NF: "Ilhas Norfolk",
  SB: "Ilhas Salomão",
  SC: "Ilhas Seychelles",
  TK: "Ilhas Tokelau",
  TC: "Ilhas Turks e Caicos",
  VI: "Ilhas Virgens (Estados Unidos)",
  VG: "Ilhas Virgens (Inglaterra)",
  IN: "Índia",
  ID: "Indonésia",
  IR: "Irã",
  IQ: "Iraque",
  IE: "Irlanda",
  IS: "Islândia",
  IL: "Israel",
  IT: "Itália",
  JM: "Jamaica",
  JP: "Japão",
  JE: "Jersey",
  JO: "Jordânia",
  KI: "Kiribati",
  XK: "Kosovo",
  KW: "Kuait",
  LA: "Laos",
  LS: "Lesoto",
  LV: "Letônia",
  LB: "Líbano",
  LR: "Libéria",
  LY: "Líbia",
  LI: "Liechtenstein",
  LT: "Lituânia",
  LU: "Luxemburgo",
  MO: "Macau",
  MK: "Macedônia (República Yugoslava)",
  MG: "Madagascar",
  MY: "Malásia",
  MW: "Malaui",
  MV: "Maldivas",
  ML: "Mali",
  MT: "Malta",
  MA: "Marrocos",
  MQ: "Martinica",
  MU: "Maurício",
  MR: "Mauritânia",
  YT: "Mayotte",
  MX: "México",
  FM: "Micronésia",
  MZ: "Moçambique",
  MD: "Moldova",
  MC: "Mônaco",
  MN: "Mongólia",
  ME: "Montenegro",
  MS: "Montserrat",
  MM: "Myanma",
  NA: "Namíbia",
  NR: "Nauru",
  NP: "Nepal",
  NI: "Nicarágua",
  NE: "Níger",
  NG: "Nigéria",
  NU: "Niue",
  NO: "Noruega",
  NC: "Nova Caledônia",
  NZ: "Nova Zelândia",
  OM: "Omã",
  BQ: "Países Baixos Caribenhos",
  PW: "Palau",
  PS: "Palestina",
  PA: "Panamá",
  PG: "Papua-Nova Guiné",
  PK: "Paquistão",
  PY: "Paraguai",
  PE: "Peru",
  PF: "Polinésia Francesa",
  PL: "Polônia",
  PR: "Porto Rico",
  PT: "Portugal",
  QA: "Qatar",
  KE: "Quênia",
  KG: "Quirguistão",
  CF: "República Centro-Africana",
  CD: "República Democrática do Congo",
  DO: "República Dominicana",
  CZ: "República Tcheca",
  RO: "Romênia",
  RW: "Ruanda",
  RU: "Rússia (antiga URSS) - Federação Russa",
  EH: "Saara Ocidental",
  PM: "Saint-Pierre e Miquelon",
  AS: "Samoa Americana",
  WS: "Samoa Ocidental",
  SM: "San Marino",
  SH: "Santa Helena",
  LC: "Santa Lúcia",
  BL: "São Bartolomeu",
  KN: "São Cristóvão e Névis",
  MF: "São Martim",
  SX: "São Martinho",
  ST: "São Tomé e Príncipe",
  VC: "São Vicente e Granadinas",
  SN: "Senegal",
  SL: "Serra Leoa",
  RS: "Sérvia",
  SY: "Síria",
  SO: "Somália",
  LK: "Sri Lanka",
  SZ: "Suazilândia",
  SD: "Sudão",
  SS: "Sudão do Sul",
  SE: "Suécia",
  CH: "Suíça",
  SR: "Suriname",
  SJ: "Svalbard",
  TJ: "Tadjiquistão",
  TH: "Tailândia",
  TW: "Taiwan",
  TZ: "Tanzânia",
  IO: "Território Britânico do Oceano índico",
  TF: "Territórios do Sul da França",
  TL: "Timor-Leste",
  TG: "Togo",
  TO: "Tonga",
  TT: "Trinidad e Tobago",
  TA: "Tristão da Cunha",
  TN: "Tunísia",
  TM: "Turcomenistão",
  TR: "Turquia",
  TV: "Tuvalu",
  UA: "Ucrânia",
  UG: "Uganda",
  UY: "Uruguai",
  UZ: "Uzbequistão",
  VU: "Vanuatu",
  VA: "Vaticano",
  VE: "Venezuela",
  VN: "Vietnã",
  WF: "Wallis e Futuna",
  ZM: "Zâmbia",
  ZW: "Zimbábue",
};

export const ufs = [
  {
    id_uf: 1,
    sigla: "AC",
    nome: "Acre",
    codigo: 12,
    id_pais: 1,
  },
  {
    id_uf: 2,
    sigla: "AL",
    nome: "Alagoas",
    codigo: 27,
    id_pais: 1,
  },
  {
    id_uf: 3,
    sigla: "AM",
    nome: "Amazonas",
    codigo: 13,
    id_pais: 1,
  },
  {
    id_uf: 4,
    sigla: "AP",
    nome: "Amapá",
    codigo: 16,
    id_pais: 1,
  },
  {
    id_uf: 5,
    sigla: "BA",
    nome: "Bahia",
    codigo: 29,
    id_pais: 1,
  },
  {
    id_uf: 6,
    sigla: "CE",
    nome: "Ceará",
    codigo: 23,
    id_pais: 1,
  },
  {
    id_uf: 7,
    sigla: "DF",
    nome: "Distrito Federal",
    codigo: 53,
    id_pais: 1,
  },
  {
    id_uf: 8,
    sigla: "ES",
    nome: "Espírito Santo",
    codigo: 32,
    id_pais: 1,
  },
  {
    id_uf: 9,
    sigla: "GO",
    nome: "Goiás",
    codigo: 52,
    id_pais: 1,
  },
  {
    id_uf: 10,
    sigla: "MA",
    nome: "Maranhão",
    codigo: 21,
    id_pais: 1,
  },
  {
    id_uf: 11,
    sigla: "MG",
    nome: "Minas Gerais",
    codigo: 31,
    id_pais: 1,
  },
  {
    id_uf: 12,
    sigla: "MS",
    nome: "Mato Grosso do Sul",
    codigo: 50,
    id_pais: 1,
  },
  {
    id_uf: 13,
    sigla: "MT",
    nome: "Mato Grosso",
    codigo: 51,
    id_pais: 1,
  },
  {
    id_uf: 14,
    sigla: "PA",
    nome: "Pará",
    codigo: 15,
    id_pais: 1,
  },
  {
    id_uf: 15,
    sigla: "PB",
    nome: "Paraíba",
    codigo: 25,
    id_pais: 1,
  },
  {
    id_uf: 16,
    sigla: "PE",
    nome: "Pernambuco",
    codigo: 26,
    id_pais: 1,
  },
  {
    id_uf: 17,
    sigla: "PI",
    nome: "Piauí",
    codigo: 22,
    id_pais: 1,
  },
  {
    id_uf: 18,
    sigla: "PR",
    nome: "Paraná",
    codigo: 41,
    id_pais: 1,
  },
  {
    id_uf: 19,
    sigla: "RJ",
    nome: "Rio de Janeiro",
    codigo: 33,
    id_pais: 1,
  },
  {
    id_uf: 20,
    sigla: "RN",
    nome: "Rio Grande do Norte",
    codigo: 24,
    id_pais: 1,
  },
  {
    id_uf: 21,
    sigla: "RO",
    nome: "Rondônia",
    codigo: 11,
    id_pais: 1,
  },
  {
    id_uf: 22,
    sigla: "RR",
    nome: "Roraima",
    codigo: 14,
    id_pais: 1,
  },
  {
    id_uf: 23,
    sigla: "RS",
    nome: "Rio Grande do Sul",
    codigo: 43,
    id_pais: 1,
  },
  {
    id_uf: 24,
    sigla: "SC",
    nome: "Santa Catarina",
    codigo: 42,
    id_pais: 1,
  },
  {
    id_uf: 25,
    sigla: "SE",
    nome: "Sergipe",
    codigo: 28,
    id_pais: 1,
  },
  {
    id_uf: 26,
    sigla: "SP",
    nome: "São Paulo",
    codigo: 35,
    id_pais: 1,
  },
  {
    id_uf: 27,
    sigla: "TO",
    nome: "Tocantins",
    codigo: 17,
    id_pais: 1,
  },
];

export function maskPhone(value: string) {
  if (!value) return value;

  // Remove all non-digits
  const digits = value.replace(/\D/g, "");

  // Limit to 11 digits
  const numbers = digits.slice(0, 11);

  if (numbers.length <= 10) {
    // (XX) XXXX-XXXX
    return numbers
      .replace(/(\d{2})(\d)/, "($1) $2")
      .replace(/(\d{4})(\d)/, "$1-$2");
  } else {
    // (XX) XXXXX-XXXX
    return numbers
      .replace(/(\d{2})(\d)/, "($1) $2")
      .replace(/(\d{5})(\d)/, "$1-$2");
  }
}
